-- Add client_message_id as a first-class column on messages so the frontend
-- can dedupe optimistic local bubbles against Realtime-arriving server rows
-- by exact id match (not the fragile text+time heuristic that breaks when
-- the network delay exceeds the lookback window).
--
-- Generated by the frontend's newClientMessageId() per outbound send and
-- forwarded through the channel-proxy /messages/send route.

ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS client_message_id TEXT;

-- Per-conversation lookup is the dedup hot path; partial index keeps the
-- index small (most rows are inbound and won't have a client_message_id).
CREATE INDEX IF NOT EXISTS idx_messages_conversation_client_id
  ON messages(conversation_id, client_message_id)
  WHERE client_message_id IS NOT NULL;
